PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;



INSERT INTO categoria (nombre, descripcion) VALUES('Alimentos','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Familia','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Animales','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Colores','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Lugares','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Transporte','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Dias de la Semana','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Partes del Cuerpo','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Sentidos','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Verbos','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Frutas','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Numeros','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Objetos del Salon','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Proceres','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Ropa','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Utiles','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Verbos AR','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Verbos ER','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Sitios Turisticos','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Adjetivos','Conocimiento Inicial');
INSERT INTO categoria (nombre, descripcion) VALUES('Verbos IR','Conocimiento Inicial');

INSERT INTO nivel (nombre, descripcion) VALUES ('Maternal', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('Prescolar', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('1er Grado', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('2do Grado', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('3er Grado', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('4to Grado', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('5to Grado', '');
INSERT INTO nivel (nombre, descripcion) VALUES ('6to Grado', '');



INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AGUA','agua.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AREPA','arepa.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GALLETA','galleta.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('HUEVO','huevo.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('JUGO','jugo.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('QUESO','queso.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SOPA','sopa.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ATOL','ATOL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ARROZ','ARROZ.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARNE','CARNE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GRANOS','GRANOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('HAMBURGUESA','HAMBURGUESA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LECHE','LECHE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PAN','PAN.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PASTA','PASTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PASTICHO','PASTICHO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PESCADO','PESCADO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIZZA','PIZZA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PLATANO','PLATANO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('POLLO','POLLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('YUCA','YUCA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CAFE','CAFE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARAOTAS','CARAOTAS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PANELA','PANELA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ENSALADA','ENSALADA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ARVEJAS','ARVEJAS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CASABE','CASABE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('EMPANADA','EMPANADA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FRIJOLES','FRIJOLES.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MORTADELA','MORTADELA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PABELLON','PABELLON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PARRILLA','PARRILLA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AUYAMA','AUYAMA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BROCOLI','BROCOLI.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CEBOLLA','CEBOLLA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CILANTRO','CILANTRO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('COLIFLOR','COLIFLOR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIMENTON','PIMENTON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TOMATE','TOMATE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ZANAHORIA','ZANAHORIA.jpg','');
INSERT INTO categoria_palabra VALUES(1,1);
INSERT INTO categoria_palabra VALUES(2,1);
INSERT INTO categoria_palabra VALUES(3,1);
INSERT INTO categoria_palabra VALUES(4,1);
INSERT INTO categoria_palabra VALUES(5,1);
INSERT INTO categoria_palabra VALUES(6,1);
INSERT INTO categoria_palabra VALUES(7,1);
INSERT INTO categoria_palabra VALUES(8,1);
INSERT INTO categoria_palabra VALUES(9,1);
INSERT INTO categoria_palabra VALUES(10,1);
INSERT INTO categoria_palabra VALUES(11,1);
INSERT INTO categoria_palabra VALUES(12,1);
INSERT INTO categoria_palabra VALUES(13,1);
INSERT INTO categoria_palabra VALUES(14,1);
INSERT INTO categoria_palabra VALUES(15,1);
INSERT INTO categoria_palabra VALUES(16,1);
INSERT INTO categoria_palabra VALUES(17,1);
INSERT INTO categoria_palabra VALUES(18,1);
INSERT INTO categoria_palabra VALUES(19,1);
INSERT INTO categoria_palabra VALUES(20,1);
INSERT INTO categoria_palabra VALUES(21,1);
INSERT INTO categoria_palabra VALUES(22,1);
INSERT INTO categoria_palabra VALUES(23,1);
INSERT INTO categoria_palabra VALUES(24,1);
INSERT INTO categoria_palabra VALUES(25,1);
INSERT INTO categoria_palabra VALUES(26,1);
INSERT INTO categoria_palabra VALUES(27,1);
INSERT INTO categoria_palabra VALUES(28,1);
INSERT INTO categoria_palabra VALUES(29,1);
INSERT INTO categoria_palabra VALUES(30,1);
INSERT INTO categoria_palabra VALUES(31,1);
INSERT INTO categoria_palabra VALUES(32,1);
INSERT INTO categoria_palabra VALUES(33,1);
INSERT INTO categoria_palabra VALUES(34,1);
INSERT INTO categoria_palabra VALUES(35,1);
INSERT INTO categoria_palabra VALUES(36,1);
INSERT INTO categoria_palabra VALUES(37,1);
INSERT INTO categoria_palabra VALUES(38,1);
INSERT INTO categoria_palabra VALUES(39,1);
INSERT INTO categoria_palabra VALUES(40,1);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ABUELA','ABUELA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ABUELO','ABUELO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BEBE','BEBE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MAMA','MAMA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PAPA','PAPA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TIA','TIA.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TIO','TIO.gif','');
INSERT INTO categoria_palabra VALUES(41,2);
INSERT INTO categoria_palabra VALUES(42,2);
INSERT INTO categoria_palabra VALUES(43,2);
INSERT INTO categoria_palabra VALUES(44,2);
INSERT INTO categoria_palabra VALUES(45,2);
INSERT INTO categoria_palabra VALUES(46,2);
INSERT INTO categoria_palabra VALUES(47,2);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CABALLO','caballo.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARACOL','caracol.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CHIVO','chivo.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('COCHINO','cochino.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ELEFANTE','elefante.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GATO','gato.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LEON','leon.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OSO','oso.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PERRO','perro.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SERPIENTE','serpiente.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TORTUGA','tortuga.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VACA','vaca.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SAPO','SAPO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GALLINA','GALLINA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GALLO','GALLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GUSANO','GUSANO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LORO','LORO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MARIPOSA','MARIPOSA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MONO','MONO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PALOMA','PALOMA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PEZ','PEZ.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('POLLITO','POLLITO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CONEJO','conejo.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BALLENA','BALLENA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BURRO','BURRO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('JIRAFA','JIRAFA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PATO','PATO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('RATON','RATON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TIGRE','TIGRE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TORO','TORO.jpg','');
INSERT INTO categoria_palabra VALUES(48,3);
INSERT INTO categoria_palabra VALUES(49,3);
INSERT INTO categoria_palabra VALUES(50,3);
INSERT INTO categoria_palabra VALUES(51,3);
INSERT INTO categoria_palabra VALUES(52,3);
INSERT INTO categoria_palabra VALUES(53,3);
INSERT INTO categoria_palabra VALUES(54,3);
INSERT INTO categoria_palabra VALUES(55,3);
INSERT INTO categoria_palabra VALUES(56,3);
INSERT INTO categoria_palabra VALUES(57,3);
INSERT INTO categoria_palabra VALUES(58,3);
INSERT INTO categoria_palabra VALUES(59,3);
INSERT INTO categoria_palabra VALUES(60,3);
INSERT INTO categoria_palabra VALUES(61,3);
INSERT INTO categoria_palabra VALUES(62,3);
INSERT INTO categoria_palabra VALUES(63,3);
INSERT INTO categoria_palabra VALUES(64,3);
INSERT INTO categoria_palabra VALUES(65,3);
INSERT INTO categoria_palabra VALUES(66,3);
INSERT INTO categoria_palabra VALUES(67,3);
INSERT INTO categoria_palabra VALUES(68,3);
INSERT INTO categoria_palabra VALUES(69,3);
INSERT INTO categoria_palabra VALUES(70,3);
INSERT INTO categoria_palabra VALUES(71,3);
INSERT INTO categoria_palabra VALUES(72,3);
INSERT INTO categoria_palabra VALUES(73,3);
INSERT INTO categoria_palabra VALUES(74,3);
INSERT INTO categoria_palabra VALUES(75,3);
INSERT INTO categoria_palabra VALUES(76,3);
INSERT INTO categoria_palabra VALUES(77,3);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AMARILLO','AMARILLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ANARANJADO','ANARANJADO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AZUL','AZUL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BLANCO','BLANCO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ROJO','ROJO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MARRON','MARRON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MORADO','MORADO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('NEGRO','NEGRO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VERDE','VERDE.jpg','');
INSERT INTO categoria_palabra VALUES(78,4);
INSERT INTO categoria_palabra VALUES(79,4);
INSERT INTO categoria_palabra VALUES(80,4);
INSERT INTO categoria_palabra VALUES(81,4);
INSERT INTO categoria_palabra VALUES(82,4);
INSERT INTO categoria_palabra VALUES(83,4);
INSERT INTO categoria_palabra VALUES(84,4);
INSERT INTO categoria_palabra VALUES(85,4);
INSERT INTO categoria_palabra VALUES(86,4);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CASA','CASA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ESCUELA','ESCUELA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PARQUE','PARQUE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PLAYA','PLAYA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARNICERIA','CARNICERIA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FARMACIA','FARMACIA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('HOSPITAL','HOSPITAL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PLAZA BOLIVAR','PLAZA BOLIVAR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('POLICIA','POLICIA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SALON','SALON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SUPERMERCADO','SUPERMERCADO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BOSQUE','BOSQUE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CAMPO','CAMPO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GRANJA','GRANJA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PUEBLO','PUEBLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VENEZUELA','VENEZUELA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CHOZA','CHOZA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SEGURO SOCIAL','SEGURO SOCIAL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DEPOSITO','DEPOSITO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('EDIFICIO','EDIFICIO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ESCALERA','ESCALERA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ESTACIONAMIENTO','ESTACIONAMIENTO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GRADAS','GRADAS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('HOTEL','HOTEL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PASILLO','PASILLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BARQUISIMETO','BARQUISIMETO.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARACAS','CARACAS.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CULATA','CULATA.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MARACAIBO','MARACAIBO.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PARAMO','PARAMO.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PUEBLO LLANO','PUEBLO LLANO.gif','');
INSERT INTO categoria_palabra VALUES(87,5);
INSERT INTO categoria_palabra VALUES(88,5);
INSERT INTO categoria_palabra VALUES(89,5);
INSERT INTO categoria_palabra VALUES(90,5);
INSERT INTO categoria_palabra VALUES(91,5);
INSERT INTO categoria_palabra VALUES(92,5);
INSERT INTO categoria_palabra VALUES(93,5);
INSERT INTO categoria_palabra VALUES(94,5);
INSERT INTO categoria_palabra VALUES(95,5);
INSERT INTO categoria_palabra VALUES(96,5);
INSERT INTO categoria_palabra VALUES(97,5);
INSERT INTO categoria_palabra VALUES(98,5);
INSERT INTO categoria_palabra VALUES(99,5);
INSERT INTO categoria_palabra VALUES(100,5);
INSERT INTO categoria_palabra VALUES(101,5);
INSERT INTO categoria_palabra VALUES(102,5);
INSERT INTO categoria_palabra VALUES(103,5);
INSERT INTO categoria_palabra VALUES(104,5);
INSERT INTO categoria_palabra VALUES(105,5);
INSERT INTO categoria_palabra VALUES(106,5);
INSERT INTO categoria_palabra VALUES(107,5);
INSERT INTO categoria_palabra VALUES(108,5);
INSERT INTO categoria_palabra VALUES(109,5);
INSERT INTO categoria_palabra VALUES(110,5);
INSERT INTO categoria_palabra VALUES(111,5);
INSERT INTO categoria_palabra VALUES(112,5);
INSERT INTO categoria_palabra VALUES(113,5);
INSERT INTO categoria_palabra VALUES(114,5);
INSERT INTO categoria_palabra VALUES(115,5);
INSERT INTO categoria_palabra VALUES(116,5);
INSERT INTO categoria_palabra VALUES(117,5);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARRO','CARRO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MOTO','MOTO.jpg','');
INSERT INTO categoria_palabra VALUES(118,6);
INSERT INTO categoria_palabra VALUES(119,6);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LUNES','LUNES.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MARTES','MARTES.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MIERCOLES','MIERCOLES.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('JUEVES','JUEVES.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VIERNES','VIERNES.gif','');
INSERT INTO categoria_palabra VALUES(120,7);
INSERT INTO categoria_palabra VALUES(121,7);
INSERT INTO categoria_palabra VALUES(122,7);
INSERT INTO categoria_palabra VALUES(123,7);
INSERT INTO categoria_palabra VALUES(124,7);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BOCA','BOCA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BRAZO','BRAZO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CABELLO','CABELLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CABEZA','CABEZA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARA','CARA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DEDOS','DEDOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIENTE','DIENTE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('HUESOS','HUESOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LENGUA','LENGUA.jpeg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MANO','MANO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('NARIZ','NARIZ.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OIDO','OIDO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OJOS','OJOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OREJA','OREJA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PELO','PELO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PENE','PENE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIE','PIE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIEL','PIEL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIERNA','PIERNA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VULVA','VULVA.jpg','');
INSERT INTO categoria_palabra VALUES(125,8);
INSERT INTO categoria_palabra VALUES(126,8);
INSERT INTO categoria_palabra VALUES(127,8);
INSERT INTO categoria_palabra VALUES(128,8);
INSERT INTO categoria_palabra VALUES(129,8);
INSERT INTO categoria_palabra VALUES(130,8);
INSERT INTO categoria_palabra VALUES(131,8);
INSERT INTO categoria_palabra VALUES(132,8);
INSERT INTO categoria_palabra VALUES(133,8);
INSERT INTO categoria_palabra VALUES(134,8);
INSERT INTO categoria_palabra VALUES(135,8);
INSERT INTO categoria_palabra VALUES(136,8);
INSERT INTO categoria_palabra VALUES(137,8);
INSERT INTO categoria_palabra VALUES(138,8);
INSERT INTO categoria_palabra VALUES(139,8);
INSERT INTO categoria_palabra VALUES(140,8);
INSERT INTO categoria_palabra VALUES(141,8);
INSERT INTO categoria_palabra VALUES(142,8);
INSERT INTO categoria_palabra VALUES(143,8);
INSERT INTO categoria_palabra VALUES(144,8);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GUSTO','GUSTO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TACTO','TACTO.jpg','');
INSERT INTO categoria_palabra VALUES(145,9);
INSERT INTO categoria_palabra VALUES(146,9);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OIR','OIR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OLER','OLER.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SENTIR','SENTIR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VER','VER.jpeg','');
INSERT INTO categoria_palabra VALUES(147,10);
INSERT INTO categoria_palabra VALUES(148,10);
INSERT INTO categoria_palabra VALUES(149,10);
INSERT INTO categoria_palabra VALUES(150,10);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CAMBUR','CAMBUR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FRESA','FRESA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LECHOZA','LECHOZA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MANGO','MANGO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MANZANA','MANZANA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MORA','MORA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PATILLA','PATILLA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PERA','PERA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('UVA','UVA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GUAYABA','GUAYABA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LIMON','LIMON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MELON','MELON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('NARANJA','NARANJA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PARCHITA','PARCHITA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIÑA','PINA.jpg','');
INSERT INTO categoria_palabra VALUES(151,11);
INSERT INTO categoria_palabra VALUES(152,11);
INSERT INTO categoria_palabra VALUES(153,11);
INSERT INTO categoria_palabra VALUES(154,11);
INSERT INTO categoria_palabra VALUES(155,11);
INSERT INTO categoria_palabra VALUES(156,11);
INSERT INTO categoria_palabra VALUES(157,11);
INSERT INTO categoria_palabra VALUES(158,11);
INSERT INTO categoria_palabra VALUES(159,11);
INSERT INTO categoria_palabra VALUES(160,11);
INSERT INTO categoria_palabra VALUES(161,11);
INSERT INTO categoria_palabra VALUES(162,11);
INSERT INTO categoria_palabra VALUES(163,11);
INSERT INTO categoria_palabra VALUES(164,11);
INSERT INTO categoria_palabra VALUES(165,11);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CATORCE','CATORCE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CIEN','CIEN.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CINCO','CINCO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CINCUENTA','CINCUENTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CUARENTA','CUARENTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CUATRO','CUATRO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIECINUEVE','DIECINUEVE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIECIOCHO','DIECIOCHO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIECISIETE','DIECISIETE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIEZ','DIEZ.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DOS','DOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('NOVENTA','NOVENTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('NUEVE','NUEVE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OCHENTA','OCHENTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OCHO','OCHO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ONCE','ONCE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('QUINCE','QUINCE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SEIS','SEIS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SESENTA','SESENTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SETENTA','SETENTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SIETE','SIETE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TRECE','TRECE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TREINTA','TREINTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TRES','TRES.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('UNO','UNO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VEINTE','VEINTE.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CIEN MIL','CIEN MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CUATROCIENTOS','CUATROCIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIECISEIS MIL','DIECISEIS MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIECISEIS','DIECISEIS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DIEZ MIL','DIEZ MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DOSCIENTOS','DOSCIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DOSCIENTOS CINCUENTA MIL','DOSCIENTOS CINCUENTA MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DOS MIL','DOS MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MIL','MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('NOVECIENTOS','NOVECIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OCHOCIENTOS','OCHOCIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OCHOCIENTOS MIL','OCHOCIENTOS MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OCHO MIL','OCHO MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('QUINIENTOS','QUINIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SEISCIENTOS','SEISCIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SETECIENTOS','SETECIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TRECIENTOS','TRECIENTOS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TRES MIL','TRES MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('UN MILLON','UN MILLON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VEINTIDOS MIL','VEINTIDOS MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VEINTISIETE MIL','VEINTISIETE MIL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DOCE','DOCE.jpg','');
INSERT INTO categoria_palabra VALUES(166,12);
INSERT INTO categoria_palabra VALUES(167,12);
INSERT INTO categoria_palabra VALUES(168,12);
INSERT INTO categoria_palabra VALUES(169,12);
INSERT INTO categoria_palabra VALUES(170,12);
INSERT INTO categoria_palabra VALUES(171,12);
INSERT INTO categoria_palabra VALUES(172,12);
INSERT INTO categoria_palabra VALUES(173,12);
INSERT INTO categoria_palabra VALUES(174,12);
INSERT INTO categoria_palabra VALUES(175,12);
INSERT INTO categoria_palabra VALUES(176,12);
INSERT INTO categoria_palabra VALUES(177,12);
INSERT INTO categoria_palabra VALUES(178,12);
INSERT INTO categoria_palabra VALUES(179,12);
INSERT INTO categoria_palabra VALUES(180,12);
INSERT INTO categoria_palabra VALUES(181,12);
INSERT INTO categoria_palabra VALUES(182,12);
INSERT INTO categoria_palabra VALUES(183,12);
INSERT INTO categoria_palabra VALUES(184,12);
INSERT INTO categoria_palabra VALUES(185,12);
INSERT INTO categoria_palabra VALUES(186,12);
INSERT INTO categoria_palabra VALUES(187,12);
INSERT INTO categoria_palabra VALUES(188,12);
INSERT INTO categoria_palabra VALUES(189,12);
INSERT INTO categoria_palabra VALUES(190,12);
INSERT INTO categoria_palabra VALUES(191,12);
INSERT INTO categoria_palabra VALUES(192,12);
INSERT INTO categoria_palabra VALUES(193,12);
INSERT INTO categoria_palabra VALUES(194,12);
INSERT INTO categoria_palabra VALUES(195,12);
INSERT INTO categoria_palabra VALUES(196,12);
INSERT INTO categoria_palabra VALUES(197,12);
INSERT INTO categoria_palabra VALUES(198,12);
INSERT INTO categoria_palabra VALUES(199,12);
INSERT INTO categoria_palabra VALUES(200,12);
INSERT INTO categoria_palabra VALUES(201,12);
INSERT INTO categoria_palabra VALUES(202,12);
INSERT INTO categoria_palabra VALUES(203,12);
INSERT INTO categoria_palabra VALUES(204,12);
INSERT INTO categoria_palabra VALUES(205,12);
INSERT INTO categoria_palabra VALUES(206,12);
INSERT INTO categoria_palabra VALUES(207,12);
INSERT INTO categoria_palabra VALUES(208,12);
INSERT INTO categoria_palabra VALUES(209,12);
INSERT INTO categoria_palabra VALUES(210,12);
INSERT INTO categoria_palabra VALUES(211,12);
INSERT INTO categoria_palabra VALUES(212,12);
INSERT INTO categoria_palabra VALUES(213,12);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BIBLIOTECA','BIBLIOTECA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CARTELERA','CARTELERA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ESCRITORIO','ESCRITORIO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MESA','MESA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PIZARRA','PIZARRA.JPG','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PUERTA','PUERTA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SILLA','SILLA.JPG','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VENTANA','VENTANA.jpg','');
INSERT INTO categoria_palabra VALUES(214,13);
INSERT INTO categoria_palabra VALUES(215,13);
INSERT INTO categoria_palabra VALUES(216,13);
INSERT INTO categoria_palabra VALUES(217,13);
INSERT INTO categoria_palabra VALUES(218,13);
INSERT INTO categoria_palabra VALUES(219,13);
INSERT INTO categoria_palabra VALUES(220,13);
INSERT INTO categoria_palabra VALUES(221,13);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ANDRES BELLO','ANDRES BELLO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('EL NEGRO PRIMERO','EL NEGRO PRIMERO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FRANCISCO DE MIRANDA','FRANCISCO DE MIRANDA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('JOSE ANTONIO PAEZ','JOSE ANTONIO PAEZ.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('RAFAEL URDANETA','RAFAEL URDANETA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SIMON BOLIVAR','SIMON BOLIVAR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SIMON RODRIGUEZ','SIMON RODRIGUEZ.jpg','');
INSERT INTO categoria_palabra VALUES(222,14);
INSERT INTO categoria_palabra VALUES(223,14);
INSERT INTO categoria_palabra VALUES(224,14);
INSERT INTO categoria_palabra VALUES(225,14);
INSERT INTO categoria_palabra VALUES(226,14);
INSERT INTO categoria_palabra VALUES(227,14);
INSERT INTO categoria_palabra VALUES(228,14);
INSERT INTO categoria_palabra VALUES(229,14);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CAMISA','CAMISA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FALDA','FALDA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FRANELA','FRANELA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MEDIAS','MEDIAS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PANTALON','PANTALON.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SHORT','SHORT.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('UNIFORME','UNIFORME.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VESTIDO','VESTIDO.jpg','');
INSERT INTO categoria_palabra VALUES(230,15);
INSERT INTO categoria_palabra VALUES(231,15);
INSERT INTO categoria_palabra VALUES(232,15);
INSERT INTO categoria_palabra VALUES(233,15);
INSERT INTO categoria_palabra VALUES(234,15);
INSERT INTO categoria_palabra VALUES(235,15);
INSERT INTO categoria_palabra VALUES(236,15);
INSERT INTO categoria_palabra VALUES(237,15);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BORRADOR','BORRADOR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CUADERNO','CUADERNO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LAPIZ','LAPIZ.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LIBRO','LIBRO.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MARCADOR','MARCADOR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MORRAL','MORRAL.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('REGLA','REGLA.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SACAPUNTAS','SACAPUNTAS.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('COLORES','COLORES.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TIJERA','TIJERA.jpg','');
INSERT INTO categoria_palabra VALUES(238,16);
INSERT INTO categoria_palabra VALUES(239,16);
INSERT INTO categoria_palabra VALUES(240,16);
INSERT INTO categoria_palabra VALUES(241,16);
INSERT INTO categoria_palabra VALUES(242,16);
INSERT INTO categoria_palabra VALUES(243,16);
INSERT INTO categoria_palabra VALUES(244,16);
INSERT INTO categoria_palabra VALUES(245,16);
INSERT INTO categoria_palabra VALUES(246,16);
INSERT INTO categoria_palabra VALUES(247,16);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AYUDAR','AYUDAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CAMINAR','CAMINAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CANTAR','CANTAR.jpg','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('COMPRAR','COMPRAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CONTAR','CONTAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DAR','DAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ENSEÑAR','ENSEÑAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ESTUDIAR','ESTUDIAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GUSTAR','GUSTAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('JUGAR','JUGAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LIMPIAR','LIMPIAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LLORAR','LLORAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PAGAR','PAGAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PEINAR','PEINAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PENSAR','PENSAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('REGALAR','REGALAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('SALTAR','SALTAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TRABAJAR','TRABAJAR.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('AMAR','AMAR.gif','');
INSERT INTO categoria_palabra VALUES(248,17);
INSERT INTO categoria_palabra VALUES(249,17);
INSERT INTO categoria_palabra VALUES(250,17);
INSERT INTO categoria_palabra VALUES(251,17);
INSERT INTO categoria_palabra VALUES(252,17);
INSERT INTO categoria_palabra VALUES(253,17);
INSERT INTO categoria_palabra VALUES(254,17);
INSERT INTO categoria_palabra VALUES(255,17);
INSERT INTO categoria_palabra VALUES(256,17);
INSERT INTO categoria_palabra VALUES(257,17);
INSERT INTO categoria_palabra VALUES(258,17);
INSERT INTO categoria_palabra VALUES(259,17);
INSERT INTO categoria_palabra VALUES(260,17);
INSERT INTO categoria_palabra VALUES(261,17);
INSERT INTO categoria_palabra VALUES(262,17);
INSERT INTO categoria_palabra VALUES(263,17);
INSERT INTO categoria_palabra VALUES(264,17);
INSERT INTO categoria_palabra VALUES(265,17);
INSERT INTO categoria_palabra VALUES(266,17);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CONOCER','CONOCER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('HACER','HACER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VENDER','VENDER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('APRENDER','APRENDER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('BEBER','BEBER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('COMER','COMER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CORRER','CORRER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DOLER','DOLER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LEER','LEER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PODER','PODER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('RESPONDER','RESPONDER.gif','');
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TENER','TENER.gif','');
INSERT INTO categoria_palabra VALUES(267,18);
INSERT INTO categoria_palabra VALUES(268,18);
INSERT INTO categoria_palabra VALUES(269,18);
INSERT INTO categoria_palabra VALUES(270,18);
INSERT INTO categoria_palabra VALUES(271,18);
INSERT INTO categoria_palabra VALUES(272,18);
INSERT INTO categoria_palabra VALUES(273,18);
INSERT INTO categoria_palabra VALUES(274,18);
INSERT INTO categoria_palabra VALUES(275,18);
INSERT INTO categoria_palabra VALUES(276,18);
INSERT INTO categoria_palabra VALUES(277,18);
INSERT INTO categoria_palabra VALUES(278,18);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VENEZUELA DE ANTIER','VENEZUELA DE ANTIER.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('CHORROS DE MILLA','CHORROS DE MILLA.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LA CATEDRAL','LA CATEDRAL.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LOCA LUZ CARABALLO','LOCA LUZ CARABALLO.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LOS ALEROS','LOS ALEROS.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MONTAÑA DE LOS SUEÑOS','MONTAÑA DE LOS SUEÑOS.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('OBSERVATORIO','OBSERVATORIO.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PLAZA DE LAS HEROINAS','PLAZA DE LAS HEROINAS.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PLAZA DE TOROS','PLAZA DE TOROS.jpg',19);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('TELEFERICO','TELEFERICO.jpg',19);
INSERT INTO categoria_palabra VALUES(279,19);
INSERT INTO categoria_palabra VALUES(280,19);
INSERT INTO categoria_palabra VALUES(281,19);
INSERT INTO categoria_palabra VALUES(282,19);
INSERT INTO categoria_palabra VALUES(283,19);
INSERT INTO categoria_palabra VALUES(284,19);
INSERT INTO categoria_palabra VALUES(285,19);
INSERT INTO categoria_palabra VALUES(286,19);
INSERT INTO categoria_palabra VALUES(287,19);
INSERT INTO categoria_palabra VALUES(288,19);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FEO','FEO.gif',20);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('FRIO','FRIO.gif',20);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('GRANDE','GRANDE.gif',20);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('LINDO','LINDO.gif',20);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MUCHO','MUCHO.gif',20);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('PEQUEÑO','PEQUEÑO.gif',20);
INSERT INTO categoria_palabra VALUES(289,20);
INSERT INTO categoria_palabra VALUES(290,20);
INSERT INTO categoria_palabra VALUES(291,20);
INSERT INTO categoria_palabra VALUES(292,20);
INSERT INTO categoria_palabra VALUES(293,20);
INSERT INTO categoria_palabra VALUES(294,20);


INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('COMPARTIR','COMPARTIR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DECIDIR','DECIDIR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('DECIR','DECIR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('ESCRIBIR','ESCRIBIR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('IR','IR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MENTIR','MENTIR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('MORIR','MORIR.gif',21);
INSERT INTO palabra (nombre, imagen, descripcion) VALUES ('VIVIR','VIVIR.gif',21);
INSERT INTO categoria_palabra VALUES(295,21);
INSERT INTO categoria_palabra VALUES(296,21);
INSERT INTO categoria_palabra VALUES(297,21);
INSERT INTO categoria_palabra VALUES(298,21);
INSERT INTO categoria_palabra VALUES(299,21);
INSERT INTO categoria_palabra VALUES(300,21);
INSERT INTO categoria_palabra VALUES(301,21);
INSERT INTO categoria_palabra VALUES(302,21);


INSERT INTO nivel_categoria VALUES(1,1);
INSERT INTO nivel_categoria VALUES(2,1);

INSERT INTO nivel_categoria VALUES(1,2);
INSERT INTO nivel_categoria VALUES(2,2);
INSERT INTO nivel_categoria VALUES(3,2);

INSERT INTO nivel_categoria VALUES(1,3);
INSERT INTO nivel_categoria VALUES(2,3);
INSERT INTO nivel_categoria VALUES(3,3);
INSERT INTO nivel_categoria VALUES(4,3);
INSERT INTO nivel_categoria VALUES(5,3);

INSERT INTO nivel_categoria VALUES(1,4);
INSERT INTO nivel_categoria VALUES(2,4);
INSERT INTO nivel_categoria VALUES(3,4);
INSERT INTO nivel_categoria VALUES(4,4);
INSERT INTO nivel_categoria VALUES(5,4);
INSERT INTO nivel_categoria VALUES(6,4);
INSERT INTO nivel_categoria VALUES(7,4);
INSERT INTO nivel_categoria VALUES(8,4);

INSERT INTO nivel_categoria VALUES(1,5);
INSERT INTO nivel_categoria VALUES(2,5);
INSERT INTO nivel_categoria VALUES(3,5);
INSERT INTO nivel_categoria VALUES(4,5);
INSERT INTO nivel_categoria VALUES(5,5);
INSERT INTO nivel_categoria VALUES(6,5);
INSERT INTO nivel_categoria VALUES(7,5);
INSERT INTO nivel_categoria VALUES(8,5);
INSERT INTO nivel_categoria VALUES(9,5);
INSERT INTO nivel_categoria VALUES(10,5);
INSERT INTO nivel_categoria VALUES(11,5);
INSERT INTO nivel_categoria VALUES(12,5);

INSERT INTO nivel_categoria VALUES(1,6);
INSERT INTO nivel_categoria VALUES(2,6);
INSERT INTO nivel_categoria VALUES(3,6);
INSERT INTO nivel_categoria VALUES(4,6);
INSERT INTO nivel_categoria VALUES(5,6);
INSERT INTO nivel_categoria VALUES(6,6);
INSERT INTO nivel_categoria VALUES(7,6);
INSERT INTO nivel_categoria VALUES(8,6);
INSERT INTO nivel_categoria VALUES(9,6);
INSERT INTO nivel_categoria VALUES(10,6);
INSERT INTO nivel_categoria VALUES(11,6);
INSERT INTO nivel_categoria VALUES(12,6);
INSERT INTO nivel_categoria VALUES(13,6);
INSERT INTO nivel_categoria VALUES(14,6);
INSERT INTO nivel_categoria VALUES(15,6);
INSERT INTO nivel_categoria VALUES(16,6);

INSERT INTO nivel_categoria VALUES(1,7);
INSERT INTO nivel_categoria VALUES(2,7);
INSERT INTO nivel_categoria VALUES(3,7);
INSERT INTO nivel_categoria VALUES(4,7);
INSERT INTO nivel_categoria VALUES(5,7);
INSERT INTO nivel_categoria VALUES(6,7);
INSERT INTO nivel_categoria VALUES(7,7);
INSERT INTO nivel_categoria VALUES(8,7);
INSERT INTO nivel_categoria VALUES(9,7);
INSERT INTO nivel_categoria VALUES(10,7);
INSERT INTO nivel_categoria VALUES(11,7);
INSERT INTO nivel_categoria VALUES(12,7);
INSERT INTO nivel_categoria VALUES(13,7);
INSERT INTO nivel_categoria VALUES(14,7);
INSERT INTO nivel_categoria VALUES(15,7);
INSERT INTO nivel_categoria VALUES(16,7);
INSERT INTO nivel_categoria VALUES(17,7);
INSERT INTO nivel_categoria VALUES(18,7);

INSERT INTO nivel_categoria VALUES(1,8);
INSERT INTO nivel_categoria VALUES(2,8);
INSERT INTO nivel_categoria VALUES(3,8);
INSERT INTO nivel_categoria VALUES(4,8);
INSERT INTO nivel_categoria VALUES(5,8);
INSERT INTO nivel_categoria VALUES(6,8);
INSERT INTO nivel_categoria VALUES(7,8);
INSERT INTO nivel_categoria VALUES(8,8);
INSERT INTO nivel_categoria VALUES(9,8);
INSERT INTO nivel_categoria VALUES(10,8);
INSERT INTO nivel_categoria VALUES(11,8);
INSERT INTO nivel_categoria VALUES(12,8);
INSERT INTO nivel_categoria VALUES(13,8);
INSERT INTO nivel_categoria VALUES(14,8);
INSERT INTO nivel_categoria VALUES(15,8);
INSERT INTO nivel_categoria VALUES(16,8);
INSERT INTO nivel_categoria VALUES(17,8);
INSERT INTO nivel_categoria VALUES(18,8);
INSERT INTO nivel_categoria VALUES(19,8);
INSERT INTO nivel_categoria VALUES(20,8);
INSERT INTO nivel_categoria VALUES(21,8);

DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Categorias',21);
INSERT INTO sqlite_sequence VALUES('Niveles',50);
COMMIT;
